baseURL = "https://mizu.reisen"
languageCode = "en-us"
title = "mizu.reisen"
theme = "cactus"
copyright = "it will be like that everytime"
enableRobotsTXT = true
# googleAnalytics = "UA-1234-5"

summaryLength = 2

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  # \themes\cactus\assets\scss\colors
  colortheme = "latte"

  favicon = "/images/favicon.ico"
  
  description = """
  I'm a security engineer and technical consultant, with a strong interest for cybersecurity and compliance.\n
  I can go by Hoang, or more friendly, mizu and reisen works too.
  """

  additional_description = """
  More about me (and my cv) can be found at 
  """

  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  mainSection = "posts" # your main section
  aboutSection = "about"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  # SEO Options
  enableOpenGraph = true
  enableTwitterCards = true
  images = ["/images/site-feature-image.jpg"]
  # Default page sharing image
  defaultSocialImage = "/images/site-feature-image.jpg"
  
  # Enhanced meta description
  metaDescription = "Security engineering, technical consulting, and cybersecurity insights by Hoang (mizu). Exploring compliance, system architecture, and security best practices."
  
  # Structured data
  [params.schema]
    type = "Person"
    name = "Hoang"
    description = "Security Engineer and Technical Consultant"
    sameAs = ["https://github.com/yourusername"]  # Add your social profiles here

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[build]
  writeStats = true
  
[build.processing]
  skip = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true