baseURL = "https://mizu.reisen"
languageCode = "en-us"
title = "mizu.reisen"
theme = "cactus"
copyright = "mizu"
disqusShortname = "home"
# googleAnalytics = "UA-1234-5"

summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  # \themes\cactus\assets\scss\colors
  colortheme = "latte"
  
  description = """
  formally i can go by Hoang, another friendly way is using my alias (mizu, reisen).\n
  currently i'm setting up the security and compliance foundation for a small org, and sometimes i do consultant projects to study different security approaches and usecases.\n
  my journal about my interests on anything so have fun if you find something interesting.
  """
  
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat
     
  # name value equals what's on https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/sakkarose"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dau-trong-hoang/"
  [[params.social]]
    name = "email"
    link = "ame@mizu.reisen"
  [[params.social]]
    name = "discord"
    link = "https://discordapp.com/users/355703385133154304"
    
[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^LASTFM_API_KEY$', '^LASTFM_USERNAME$']