baseURL = "https://mizu.reisen"
languageCode = "en-us"
title = "mizu.reisen"
theme = "cactus"
copyright = "it will be like that everytime"
disqusShortname = "home"
enableRobotsTXT = true
# googleAnalytics = "UA-1234-5"

summaryLength = 2

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  # \themes\cactus\assets\scss\colors
  colortheme = "latte"
  
  description = """
  formally i can go by Hoang, another friendly way is using my alias (mizu, reisen).\n
  currently i'm setting up the security and compliance foundation for a small org, and sometimes i do consultant projects to study different security approaches and usecases.\n
  my journal is about my interests in anything so i hope u have fun when you find something interesting.\n
  i can be reached through
  """
  
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default
    
[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']