baseURL = "https://mizu.reisen"
languageCode = "en-us"
title = "mizu.reisen"
theme = "cactus"
copyright = "it will be like that everytime"
enableRobotsTXT = true
# googleAnalytics = "UA-1234-5"

summaryLength = 2

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  # \themes\cactus\assets\scss\colors
  colortheme = "latte"

  favicon = "favicon.ico"
  
  description = """
  i'm a security engineer and technical consultant, with a strong interest for cybersecurity and compliance.\n
  i can go by Hoang, or more friendly, mizu and reisen works too.\n
  """

  additional_description = """
  more about me (and my cv) can be found at 
  """

  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  mainSection = "posts" # your main section
  aboutSection = "about"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']