name: Cache Last.fm Data

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-lastfm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Fetch Last.fm data
        run: |
          response=$(curl -s '${{ secrets.LASTFM_WORKER_URL }}')
          echo "$response" > static/js/lastfm-data.json
          
      - name: Check for changes
        id: verify-changed
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          
      - name: Commit and push if changed
        if: steps.verify-changed.outputs.changes_exist == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add static/js/lastfm-data.json
          git commit -m "Update Last.fm data"
          git push
